services:
  app:
    image: asomaaroufiniyaa/todo-api-app
    container_name: todo-app
    environment:
      - MONGO_URL=mongodb://mongo:27017/todo_db
    depends_on:
      - mongo

  mongo:
    image: mongo:latest
    container_name: mongo-db
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  nginx:
    image: nginx:alpine
    container_name: nginx-proxy
    ports:
      - "80:80"
    volumes:
      - /home/ubuntu/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - app

volumes:
  mongo_data:
