---
- name: Deploy application
  hosts: web_servers
  become: true 
  tasks:
    - name: Pull Docker image from Docker Hub
      community.docker.docker_image:
        name: asomaaroufiniyaa/todo-app-api:latest
        source: pull

    - name: Copy docker-compose file to server
      copy:
        src: ../../app/docker-compose.yml
        dest: /home/ubuntu/docker-compose.yml
        owner: ubuntu
        group: ubuntu
        mode: '0644'

    - name: Run docker-compose v2 to start containers
      community.docker.docker_compose_v2:
        project_src: /home/ubuntu
        files:
          - docker-compose.yml
        state: present
        restarted: true
