name: Deploy App
on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2

      - name: Setup Terraform SSH Key
        run: |
          mkdir -p terraform/keys
          echo "${{ secrets.SSH_PUBLIC_KEY }}" > terraform/keys/id_ed25519.pub

      - name: Terraform Init
        run: terraform -chdir=terraform init

      - name: Terraform Apply
        run: terraform -chdir=terraform apply -auto-approve
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: "eu-north-1"

      - name: Setup SSH Key for Ansible
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.DEPLOY_KEY }}" > ~/.ssh/deploy-key.pem
          chmod 600 ~/.ssh/deploy-key.pem

      - name: Setup Ansible
        run: |
          sudo apt update
          sudo apt install ansible -y

      - name: Run Ansible Playbooks
        run: |
          ansible-playbook ansible/playbooks/setup.yml
          ansible-playbook ansible/playbooks/deploy.yml
        env:
          ANSIBLE_HOST_KEY_CHECKING: False
